TRAIN:
  ENABLE: True
  DATASET: mmit
  BATCH_SIZE: 64
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  ENABLE_AMP: True
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [128, 160]
  TRAIN_CROP_SIZE: 112
  TEST_CROP_SIZE: 128
  INPUT_CHANNEL_NUM: [3]
  MULTI_LABEL: True
  PATH_LABEL_SEPARATOR: ","
  ENSEMBLE_METHOD: max
M3A:
  MODE: GRAPH
  MODAL_TYPE: RGB_AUDIO_TEXT
  MODAL_JOINT_TYPE: SUM
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.01
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 12, 24, 30]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 30
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 0.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 313
  ARCH: r2plus1d
  DEPTH: 34
  MODEL_NAME: M3ANET
  LOSS_FUNC: bce_logit
  HEAD_ACT: sigmoid
  DROPOUT_RATE: 0.0
TEST:
  ENABLE: True
  DATASET: mmit
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
LOG_MODEL_INFO: True
